require('dotenv').config();
const mongoose = require('mongoose');
const bcrypt   = require('bcryptjs');
const User     = require('../models/User');
const { JobRole } = require('../models/index');

const ROLES = [
  // ── TECHNOLOGY ──────────────────────────────────────────────────────────
  { roleName:'Software Engineer',          category:'Technology',           icon:'💻', description:'Design and build scalable software systems.', avgSalary:'$110,000', growth:'High',      requiredSkills:[{skill:'Python',weight:.2},{skill:'Java',weight:.15},{skill:'JavaScript',weight:.15},{skill:'Data Structures',weight:.15},{skill:'Algorithms',weight:.1},{skill:'Git',weight:.1},{skill:'SQL',weight:.1},{skill:'REST API',weight:.05}], relatedInterests:['programming','technology','software'], educationMatch:['computer science','software engineering'], keyResources:['LeetCode','CS50','The Odin Project'] },
  { roleName:'Full Stack Developer',       category:'Technology',           icon:'🌐', description:'Build complete web applications frontend and backend.', avgSalary:'$105,000', growth:'High',      requiredSkills:[{skill:'JavaScript',weight:.25},{skill:'React',weight:.2},{skill:'Node.js',weight:.15},{skill:'HTML',weight:.1},{skill:'CSS',weight:.1},{skill:'SQL',weight:.1},{skill:'Git',weight:.1}], relatedInterests:['web development','programming'], educationMatch:['computer science'], keyResources:['freeCodeCamp','MDN'] },
  { roleName:'Backend Engineer',           category:'Technology',           icon:'⚙️', description:'Design and implement server-side APIs and databases.', avgSalary:'$115,000', growth:'High',      requiredSkills:[{skill:'Node.js',weight:.2},{skill:'Python',weight:.2},{skill:'SQL',weight:.15},{skill:'REST API',weight:.15},{skill:'Docker',weight:.1},{skill:'PostgreSQL',weight:.1},{skill:'Redis',weight:.1}], relatedInterests:['backend','systems','APIs'], educationMatch:['computer science'], keyResources:['Backend Roadmap'] },
  { roleName:'Frontend Engineer',          category:'Technology',           icon:'🖥️', description:'Build beautiful and responsive user interfaces.', avgSalary:'$100,000', growth:'High',      requiredSkills:[{skill:'React',weight:.25},{skill:'TypeScript',weight:.2},{skill:'CSS',weight:.15},{skill:'JavaScript',weight:.15},{skill:'HTML',weight:.1},{skill:'Figma',weight:.15}], relatedInterests:['UI','design','web'], educationMatch:['computer science','design'], keyResources:['React Docs','CSS Tricks'] },
  { roleName:'iOS Developer',              category:'Technology',           icon:'📱', description:'Build native iOS applications in Swift.', avgSalary:'$115,000', growth:'High',      requiredSkills:[{skill:'Swift',weight:.35},{skill:'iOS',weight:.25},{skill:'Xcode',weight:.15},{skill:'UIKit',weight:.15},{skill:'REST API',weight:.1}], relatedInterests:['mobile','apple'], educationMatch:['computer science'], keyResources:['Apple Developer','Hacking with Swift'] },
  { roleName:'Android Developer',          category:'Technology',           icon:'🤖', description:'Build native Android applications in Kotlin.', avgSalary:'$110,000', growth:'High',      requiredSkills:[{skill:'Kotlin',weight:.35},{skill:'Android',weight:.25},{skill:'Java',weight:.1},{skill:'REST API',weight:.1},{skill:'Firebase',weight:.2}], relatedInterests:['mobile','android'], educationMatch:['computer science'], keyResources:['Android Developers'] },
  // ── AI & ML ─────────────────────────────────────────────────────────────
  { roleName:'Machine Learning Engineer',  category:'AI & Machine Learning', icon:'🤖', description:'Develop and deploy production ML/AI systems.', avgSalary:'$130,000', growth:'Very High', requiredSkills:[{skill:'Python',weight:.25},{skill:'TensorFlow',weight:.15},{skill:'PyTorch',weight:.15},{skill:'Machine Learning',weight:.2},{skill:'Deep Learning',weight:.1},{skill:'SQL',weight:.1},{skill:'Docker',weight:.05}], relatedInterests:['AI','machine learning','research'], educationMatch:['computer science','data science'], keyResources:['Fast.ai','Papers With Code'] },
  { roleName:'Data Scientist',             category:'AI & Machine Learning', icon:'📊', description:'Extract insights from data and build predictive models.', avgSalary:'$120,000', growth:'Very High', requiredSkills:[{skill:'Python',weight:.25},{skill:'Machine Learning',weight:.2},{skill:'Statistics',weight:.15},{skill:'SQL',weight:.15},{skill:'Pandas',weight:.1},{skill:'NumPy',weight:.05},{skill:'Visualization',weight:.1}], relatedInterests:['data','analytics','mathematics'], educationMatch:['data science','statistics','mathematics'], keyResources:['Kaggle','DataCamp'] },
  { roleName:'AI Research Scientist',      category:'AI & Machine Learning', icon:'🔬', description:'Conduct research to advance the state of AI.', avgSalary:'$150,000', growth:'Very High', requiredSkills:[{skill:'Python',weight:.2},{skill:'PyTorch',weight:.2},{skill:'Deep Learning',weight:.2},{skill:'Mathematics',weight:.15},{skill:'Research',weight:.1},{skill:'Publications',weight:.1},{skill:'CUDA',weight:.05}], relatedInterests:['research','AI','mathematics'], educationMatch:['computer science','mathematics'], keyResources:['NeurIPS','arXiv'] },
  { roleName:'NLP Engineer',               category:'AI & Machine Learning', icon:'💬', description:'Build natural language processing systems and LLMs.', avgSalary:'$135,000', growth:'Very High', requiredSkills:[{skill:'Python',weight:.2},{skill:'NLP',weight:.25},{skill:'Transformers',weight:.2},{skill:'LLM',weight:.15},{skill:'PyTorch',weight:.1},{skill:'HuggingFace',weight:.1}], relatedInterests:['NLP','linguistics','AI'], educationMatch:['computer science'], keyResources:['Hugging Face','ACL Anthology'] },
  { roleName:'Generative AI Engineer',     category:'AI & Machine Learning', icon:'✨', description:'Build applications using LLMs, RAG, and generative AI.', avgSalary:'$140,000', growth:'Very High', requiredSkills:[{skill:'Python',weight:.2},{skill:'LLM',weight:.25},{skill:'LangChain',weight:.15},{skill:'RAG',weight:.15},{skill:'Embeddings',weight:.1},{skill:'Prompt Engineering',weight:.15}], relatedInterests:['GenAI','LLMs','AI'], educationMatch:['computer science'], keyResources:['LangChain Docs','OpenAI Cookbook'] },
  { roleName:'MLOps Engineer',             category:'AI & Machine Learning', icon:'🔧', description:'Build infrastructure for training and serving ML models.', avgSalary:'$125,000', growth:'Very High', requiredSkills:[{skill:'Python',weight:.2},{skill:'Docker',weight:.15},{skill:'Kubernetes',weight:.15},{skill:'MLflow',weight:.1},{skill:'AWS',weight:.15},{skill:'CI/CD',weight:.1},{skill:'Machine Learning',weight:.15}], relatedInterests:['MLOps','infrastructure','AI'], educationMatch:['computer science'], keyResources:['MLflow Docs','Kubeflow'] },
  // ── DATA ────────────────────────────────────────────────────────────────
  { roleName:'Data Engineer',              category:'Data & Analytics',      icon:'🔀', description:'Build data pipelines and infrastructure.', avgSalary:'$115,000', growth:'Very High', requiredSkills:[{skill:'Python',weight:.2},{skill:'SQL',weight:.2},{skill:'Spark',weight:.15},{skill:'Airflow',weight:.1},{skill:'AWS',weight:.15},{skill:'dbt',weight:.1},{skill:'Kafka',weight:.1}], relatedInterests:['data','infrastructure','pipelines'], educationMatch:['computer science','data science'], keyResources:['dbt Docs','Airflow Docs'] },
  { roleName:'Data Analyst',               category:'Data & Analytics',      icon:'🔍', description:'Analyze data to support business decisions.', avgSalary:'$75,000',  growth:'Medium',   requiredSkills:[{skill:'SQL',weight:.3},{skill:'Excel',weight:.2},{skill:'Python',weight:.15},{skill:'Tableau',weight:.15},{skill:'Statistics',weight:.1},{skill:'Communication',weight:.1}], relatedInterests:['analytics','data','business'], educationMatch:['statistics','business','data science'], keyResources:['Kaggle','DataCamp'] },
  { roleName:'Business Intelligence Developer', category:'Data & Analytics', icon:'📉', description:'Build dashboards and reports for business decisions.', avgSalary:'$90,000',  growth:'Medium',   requiredSkills:[{skill:'SQL',weight:.3},{skill:'Tableau',weight:.2},{skill:'Power BI',weight:.2},{skill:'Data Modeling',weight:.15},{skill:'Excel',weight:.15}], relatedInterests:['analytics','reporting','business'], educationMatch:['business','information systems'], keyResources:['Tableau Training','Power BI Docs'] },
  // ── CLOUD ────────────────────────────────────────────────────────────────
  { roleName:'Cloud Engineer',             category:'Cloud & Infrastructure', icon:'☁️', description:'Design and manage cloud infrastructure.', avgSalary:'$115,000', growth:'Very High', requiredSkills:[{skill:'AWS',weight:.25},{skill:'Docker',weight:.2},{skill:'Kubernetes',weight:.15},{skill:'Linux',weight:.15},{skill:'Terraform',weight:.1},{skill:'Python',weight:.1},{skill:'CI/CD',weight:.05}], relatedInterests:['cloud','infrastructure'], educationMatch:['computer science','IT'], keyResources:['AWS Training','A Cloud Guru'] },
  { roleName:'DevOps Engineer',            category:'Cloud & Infrastructure', icon:'⚙️', description:'Bridge development and operations for fast delivery.', avgSalary:'$108,000', growth:'High',      requiredSkills:[{skill:'Docker',weight:.2},{skill:'Kubernetes',weight:.15},{skill:'CI/CD',weight:.2},{skill:'Linux',weight:.15},{skill:'AWS',weight:.1},{skill:'Python',weight:.1},{skill:'Bash',weight:.1}], relatedInterests:['automation','infrastructure'], educationMatch:['computer science','IT'], keyResources:['DevOps Bootcamp','Linux Foundation'] },
  { roleName:'Site Reliability Engineer',  category:'Cloud & Infrastructure', icon:'🛡️', description:'Ensure reliability and performance of large-scale systems.', avgSalary:'$130,000', growth:'Very High', requiredSkills:[{skill:'Linux',weight:.2},{skill:'Python',weight:.15},{skill:'Kubernetes',weight:.15},{skill:'Monitoring',weight:.15},{skill:'Go',weight:.1},{skill:'AWS',weight:.15},{skill:'Incident Response',weight:.1}], relatedInterests:['reliability','infrastructure'], educationMatch:['computer science'], keyResources:['Google SRE Book'] },
  { roleName:'Solutions Architect',        category:'Cloud & Infrastructure', icon:'🏗️', description:'Design complex enterprise technical solutions.', avgSalary:'$140,000', growth:'High',      requiredSkills:[{skill:'AWS',weight:.25},{skill:'Architecture',weight:.2},{skill:'Communication',weight:.15},{skill:'Security',weight:.1},{skill:'Networking',weight:.1},{skill:'Databases',weight:.1},{skill:'Cost Optimization',weight:.1}], relatedInterests:['cloud','architecture','enterprise'], educationMatch:['computer science','engineering'], keyResources:['AWS Solutions Architect'] },
  // ── SECURITY ─────────────────────────────────────────────────────────────
  { roleName:'Cybersecurity Analyst',      category:'Cybersecurity',         icon:'🔒', description:'Protect systems and data from cyber threats.', avgSalary:'$100,000', growth:'Very High', requiredSkills:[{skill:'Networking',weight:.2},{skill:'Linux',weight:.15},{skill:'Security',weight:.2},{skill:'Python',weight:.1},{skill:'Risk Assessment',weight:.1},{skill:'Penetration Testing',weight:.1},{skill:'Firewalls',weight:.15}], relatedInterests:['security','networking'], educationMatch:['cybersecurity','computer science'], keyResources:['TryHackMe','HackTheBox'] },
  { roleName:'Security Engineer',          category:'Cybersecurity',         icon:'🛡️', description:'Build security systems and conduct vulnerability assessments.', avgSalary:'$120,000', growth:'Very High', requiredSkills:[{skill:'Security',weight:.25},{skill:'Python',weight:.15},{skill:'Networking',weight:.15},{skill:'Linux',weight:.1},{skill:'Cryptography',weight:.1},{skill:'Penetration Testing',weight:.1},{skill:'Cloud Security',weight:.15}], relatedInterests:['security','hacking'], educationMatch:['cybersecurity'], keyResources:['SANS','Offensive Security'] },
  { roleName:'Penetration Tester',         category:'Cybersecurity',         icon:'⚔️', description:'Find vulnerabilities by simulating cyberattacks.', avgSalary:'$110,000', growth:'Very High', requiredSkills:[{skill:'Penetration Testing',weight:.35},{skill:'Kali Linux',weight:.2},{skill:'Python',weight:.15},{skill:'Networking',weight:.15},{skill:'Metasploit',weight:.15}], relatedInterests:['ethical hacking','security'], educationMatch:['cybersecurity'], keyResources:['OSCP','HackTheBox'] },
  { roleName:'AI Security Researcher',     category:'Cybersecurity',         icon:'🔐', description:'Research AI model security, adversarial attacks, and TEE systems.', avgSalary:'$130,000', growth:'Very High', requiredSkills:[{skill:'Python',weight:.2},{skill:'PyTorch',weight:.15},{skill:'Machine Learning',weight:.15},{skill:'Linux',weight:.15},{skill:'Security',weight:.15},{skill:'RISC-V',weight:.1},{skill:'Edge Computing',weight:.1}], relatedInterests:['AI security','research','edge'], educationMatch:['computer science'], keyResources:['arXiv Security','IEEE S&P'] },
  // ── PRODUCT ──────────────────────────────────────────────────────────────
  { roleName:'Product Manager',            category:'Product & Business',    icon:'🗺️', description:'Lead product vision and drive roadmap execution.', avgSalary:'$125,000', growth:'High',      requiredSkills:[{skill:'Product Strategy',weight:.25},{skill:'Agile',weight:.2},{skill:'Communication',weight:.2},{skill:'Analytics',weight:.15},{skill:'Roadmapping',weight:.1},{skill:'Stakeholder Management',weight:.1}], relatedInterests:['business','strategy','leadership'], educationMatch:['business','computer science','mba'], keyResources:['Product School','Reforge'] },
  { roleName:'Business Analyst',           category:'Product & Business',    icon:'📈', description:'Analyze business processes and requirements.', avgSalary:'$80,000',  growth:'Medium',   requiredSkills:[{skill:'SQL',weight:.25},{skill:'Excel',weight:.2},{skill:'Requirements Analysis',weight:.2},{skill:'Communication',weight:.15},{skill:'Data Analysis',weight:.1},{skill:'Documentation',weight:.1}], relatedInterests:['business','analytics'], educationMatch:['business','information systems'], keyResources:['IIBA','Coursera'] },
  // ── DESIGN ───────────────────────────────────────────────────────────────
  { roleName:'UX/UI Designer',             category:'Design & Creative',     icon:'🎨', description:'Design user interfaces and experiences.', avgSalary:'$90,000',  growth:'Medium',   requiredSkills:[{skill:'Figma',weight:.3},{skill:'User Research',weight:.2},{skill:'Wireframing',weight:.15},{skill:'Prototyping',weight:.15},{skill:'Design Thinking',weight:.1},{skill:'CSS',weight:.1}], relatedInterests:['design','creativity','UX'], educationMatch:['design','HCI'], keyResources:['Nielsen Norman','Figma Academy'] },
  { roleName:'Graphic Designer',           category:'Design & Creative',     icon:'🖌️', description:'Create visual content for digital and print media.', avgSalary:'$55,000',  growth:'Low',      requiredSkills:[{skill:'Adobe Photoshop',weight:.25},{skill:'Adobe Illustrator',weight:.25},{skill:'Typography',weight:.15},{skill:'Color Theory',weight:.15},{skill:'Branding',weight:.1},{skill:'Layout Design',weight:.1}], relatedInterests:['art','design','creativity'], educationMatch:['graphic design'], keyResources:['Behance','Adobe Learn'] },
  // ── MARKETING ────────────────────────────────────────────────────────────
  { roleName:'Digital Marketing Manager',  category:'Marketing',             icon:'📣', description:'Plan and execute digital marketing strategies.', avgSalary:'$80,000',  growth:'High',      requiredSkills:[{skill:'SEO',weight:.2},{skill:'Google Ads',weight:.15},{skill:'Social Media',weight:.15},{skill:'Analytics',weight:.15},{skill:'Email Marketing',weight:.1},{skill:'Content Marketing',weight:.1},{skill:'Marketing Strategy',weight:.15}], relatedInterests:['marketing','digital','growth'], educationMatch:['marketing','business'], keyResources:['HubSpot Academy','Google Digital Garage'] },
  { roleName:'SEO Specialist',             category:'Marketing',             icon:'🔎', description:'Optimize websites for search engine visibility.', avgSalary:'$60,000',  growth:'Medium',   requiredSkills:[{skill:'SEO',weight:.35},{skill:'Google Analytics',weight:.2},{skill:'Keyword Research',weight:.15},{skill:'Technical SEO',weight:.15},{skill:'Content Marketing',weight:.15}], relatedInterests:['SEO','digital marketing'], educationMatch:['marketing'], keyResources:['Moz','Ahrefs Blog'] },
  // ── FINANCE ──────────────────────────────────────────────────────────────
  { roleName:'Financial Analyst',          category:'Finance',               icon:'💰', description:'Analyze financial data and create investment models.', avgSalary:'$80,000',  growth:'Medium',   requiredSkills:[{skill:'Excel',weight:.25},{skill:'Financial Modeling',weight:.25},{skill:'SQL',weight:.15},{skill:'Accounting',weight:.15},{skill:'Valuation',weight:.1},{skill:'PowerPoint',weight:.1}], relatedInterests:['finance','investments'], educationMatch:['finance','accounting','economics'], keyResources:['CFA Institute','Wall Street Prep'] },
  { roleName:'Quantitative Analyst',       category:'Finance',               icon:'📐', description:'Use mathematical models to analyze financial markets.', avgSalary:'$140,000', growth:'High',      requiredSkills:[{skill:'Python',weight:.2},{skill:'Statistics',weight:.25},{skill:'Mathematics',weight:.2},{skill:'Machine Learning',weight:.15},{skill:'R',weight:.1},{skill:'Financial Markets',weight:.1}], relatedInterests:['finance','mathematics'], educationMatch:['mathematics','physics','finance'], keyResources:['QuantLib','Wilmott'] },
  // ── HEALTHCARE ───────────────────────────────────────────────────────────
  { roleName:'Healthcare Data Analyst',    category:'Healthcare',            icon:'🏥', description:'Analyze health data to improve patient outcomes.', avgSalary:'$75,000',  growth:'High',      requiredSkills:[{skill:'SQL',weight:.25},{skill:'Python',weight:.2},{skill:'Healthcare IT',weight:.15},{skill:'Statistics',weight:.15},{skill:'Excel',weight:.1},{skill:'HIPAA',weight:.15}], relatedInterests:['healthcare','data','medicine'], educationMatch:['health informatics','data science'], keyResources:['AMIA','Health Data Management'] },
  { roleName:'Health IT Specialist',       category:'Healthcare',            icon:'💻', description:'Manage healthcare information systems and EHR.', avgSalary:'$80,000',  growth:'High',      requiredSkills:[{skill:'EHR Systems',weight:.25},{skill:'Healthcare IT',weight:.2},{skill:'Project Management',weight:.15},{skill:'HIPAA',weight:.1},{skill:'SQL',weight:.1},{skill:'Networking',weight:.2}], relatedInterests:['healthcare','technology'], educationMatch:['health informatics','computer science'], keyResources:['HIMSS','Epic Training'] },
  // ── EDUCATION ────────────────────────────────────────────────────────────
  { roleName:'Instructional Designer',     category:'Education',             icon:'📚', description:'Design effective learning experiences and curricula.', avgSalary:'$65,000',  growth:'Medium',   requiredSkills:[{skill:'Instructional Design',weight:.3},{skill:'E-Learning Tools',weight:.2},{skill:'Curriculum Development',weight:.2},{skill:'LMS',weight:.15},{skill:'Communication',weight:.15}], relatedInterests:['education','teaching','design'], educationMatch:['education'], keyResources:['ATD','eLearning Industry'] },
  { roleName:'Research Scientist',         category:'Research & Science',    icon:'🔬', description:'Conduct cutting-edge research in specialized fields.', avgSalary:'$100,000', growth:'High',      requiredSkills:[{skill:'Research Methodology',weight:.25},{skill:'Data Analysis',weight:.2},{skill:'Python',weight:.15},{skill:'Statistics',weight:.15},{skill:'Technical Writing',weight:.1},{skill:'Laboratory Skills',weight:.15}], relatedInterests:['research','science'], educationMatch:['PhD in any field'], keyResources:['Google Scholar','ResearchGate'] },
  // ── ENGINEERING ──────────────────────────────────────────────────────────
  { roleName:'Mechanical Engineer',        category:'Engineering',           icon:'⚙️', description:'Design and build mechanical systems and products.', avgSalary:'$85,000',  growth:'Medium',   requiredSkills:[{skill:'CAD',weight:.25},{skill:'SolidWorks',weight:.2},{skill:'FEA',weight:.15},{skill:'Thermodynamics',weight:.1},{skill:'Materials Science',weight:.1},{skill:'MATLAB',weight:.1},{skill:'GD&T',weight:.1}], relatedInterests:['engineering','manufacturing'], educationMatch:['mechanical engineering'], keyResources:['ASME'] },
  { roleName:'Electrical Engineer',        category:'Engineering',           icon:'⚡', description:'Design and develop electrical systems and electronics.', avgSalary:'$90,000',  growth:'Medium',   requiredSkills:[{skill:'Circuit Design',weight:.25},{skill:'PCB Design',weight:.2},{skill:'Embedded Systems',weight:.15},{skill:'Signal Processing',weight:.15},{skill:'MATLAB',weight:.15},{skill:'VHDL',weight:.1}], relatedInterests:['electronics','engineering'], educationMatch:['electrical engineering'], keyResources:['IEEE'] },
  { roleName:'Embedded Systems Engineer',  category:'Engineering',           icon:'💾', description:'Develop firmware and software for embedded hardware.', avgSalary:'$100,000', growth:'High',      requiredSkills:[{skill:'C',weight:.25},{skill:'C++',weight:.2},{skill:'Embedded Systems',weight:.2},{skill:'RTOS',weight:.15},{skill:'Microcontrollers',weight:.1},{skill:'Assembly',weight:.1}], relatedInterests:['embedded','hardware','firmware'], educationMatch:['electrical engineering','computer engineering'], keyResources:['Embedded.com'] },
  { roleName:'Robotics Engineer',          category:'Engineering',           icon:'🤖', description:'Design and build robotic systems and autonomous machines.', avgSalary:'$110,000', growth:'Very High', requiredSkills:[{skill:'ROS',weight:.25},{skill:'Python',weight:.15},{skill:'C++',weight:.15},{skill:'Computer Vision',weight:.1},{skill:'Control Systems',weight:.15},{skill:'SLAM',weight:.1},{skill:'Machine Learning',weight:.1}], relatedInterests:['robotics','AI','automation'], educationMatch:['robotics','computer science'], keyResources:['ROS Wiki'] },
  // ── SALES ────────────────────────────────────────────────────────────────
  { roleName:'Sales Engineer',             category:'Sales',                 icon:'🔧', description:'Bridge technical expertise and sales for complex products.', avgSalary:'$100,000', growth:'High',      requiredSkills:[{skill:'Technical Sales',weight:.25},{skill:'Communication',weight:.2},{skill:'Product Knowledge',weight:.2},{skill:'Solution Design',weight:.15},{skill:'CRM',weight:.1},{skill:'Demos',weight:.1}], relatedInterests:['sales','technology','engineering'], educationMatch:['computer science','engineering'], keyResources:['SE Nation'] },
  { roleName:'Account Executive',          category:'Sales',                 icon:'🤝', description:'Drive revenue by managing client relationships.', avgSalary:'$80,000',  growth:'Medium',   requiredSkills:[{skill:'Sales',weight:.3},{skill:'CRM',weight:.2},{skill:'Negotiation',weight:.2},{skill:'Communication',weight:.15},{skill:'Prospecting',weight:.15}], relatedInterests:['sales','business'], educationMatch:['business'], keyResources:['Salesforce Trailhead'] },
  // ── HUMAN RESOURCES ──────────────────────────────────────────────────────
  { roleName:'Recruiter',                  category:'Human Resources',       icon:'👥', description:'Source, screen, and hire top talent.', avgSalary:'$65,000',  growth:'Medium',   requiredSkills:[{skill:'Recruiting',weight:.3},{skill:'Interviewing',weight:.2},{skill:'ATS',weight:.15},{skill:'Communication',weight:.15},{skill:'LinkedIn',weight:.1},{skill:'Sourcing',weight:.1}], relatedInterests:['recruiting','HR','people'], educationMatch:['HR','business'], keyResources:['SHRM'] },
  { roleName:'HR Business Partner',        category:'Human Resources',       icon:'🤝', description:'Align HR strategy with business objectives.', avgSalary:'$85,000',  growth:'Medium',   requiredSkills:[{skill:'HR Strategy',weight:.25},{skill:'Employee Relations',weight:.2},{skill:'Performance Management',weight:.2},{skill:'Communication',weight:.15},{skill:'Labor Law',weight:.1},{skill:'Coaching',weight:.1}], relatedInterests:['HR','business'], educationMatch:['HR','business'], keyResources:['SHRM','Gallup'] },
  // ── MEDIA ────────────────────────────────────────────────────────────────
  { roleName:'Technical Writer',           category:'Media & Communications',icon:'✍️', description:'Create clear documentation for technical products.', avgSalary:'$75,000',  growth:'Medium',   requiredSkills:[{skill:'Technical Writing',weight:.35},{skill:'Documentation',weight:.25},{skill:'API Documentation',weight:.15},{skill:'Markdown',weight:.1},{skill:'Research',weight:.15}], relatedInterests:['writing','technology'], educationMatch:['technical writing','English'], keyResources:['Write the Docs','STC'] },
  { roleName:'Content Creator',            category:'Media & Communications',icon:'📸', description:'Create digital content across platforms.', avgSalary:'$50,000',  growth:'High',      requiredSkills:[{skill:'Content Strategy',weight:.2},{skill:'Social Media',weight:.2},{skill:'Photography',weight:.15},{skill:'Copywriting',weight:.15},{skill:'SEO',weight:.15},{skill:'Video Production',weight:.15}], relatedInterests:['content','social media'], educationMatch:['communications','marketing'], keyResources:['Buffer Blog'] },
  // ── ENVIRONMENT ──────────────────────────────────────────────────────────
  { roleName:'Graduate Research Assistant',  category:'Research & Science',    icon:'🎓', description:'Conduct AI/ML research at a university lab under faculty supervision.', avgSalary:'$28,000', growth:'Medium', requiredSkills:[{skill:'Python',weight:.25},{skill:'Machine Learning',weight:.2},{skill:'Research',weight:.2},{skill:'TensorFlow',weight:.1},{skill:'PyTorch',weight:.1},{skill:'Data Analysis',weight:.1},{skill:'Technical Writing',weight:.05}], relatedInterests:['research','AI','academia'], educationMatch:['computer science','data science'], keyResources:["arXiv",'Google Scholar','Kaggle'] },
  { roleName:'Environmental Consultant',   category:'Environment',           icon:'🌿', description:'Advise organizations on environmental compliance.', avgSalary:'$75,000',  growth:'High',      requiredSkills:[{skill:'Environmental Science',weight:.3},{skill:'Regulatory Compliance',weight:.2},{skill:'Data Analysis',weight:.15},{skill:'GIS',weight:.1},{skill:'Report Writing',weight:.15},{skill:'Project Management',weight:.1}], relatedInterests:['environment','sustainability'], educationMatch:['environmental science'], keyResources:['EPA Guidance'] },
];

async function seed() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('Connected to MongoDB');

  await mongoose.connection.collection('jobroles').deleteMany({});
  await JobRole.insertMany(ROLES.map(r => ({ ...r, isActive: true })));
  console.log(`✅ Seeded ${ROLES.length} job roles across ${[...new Set(ROLES.map(r=>r.category))].length} categories`);
  console.log('   Categories:', [...new Set(ROLES.map(r=>r.category))].join(', '));

  // Admin
  const adminExists = await User.findOne({ email: 'admin@careerassist.com' });
  if (!adminExists) {
    await User.create({ name:'Admin', email:'admin@careerassist.com', passwordHash: await bcrypt.hash('Admin@123', 12), role:'admin' });
    console.log('✅ Admin: admin@careerassist.com / Admin@123');
  }

  // Demo student
  const demoExists = await User.findOne({ email: 'demo@student.com' });
  if (!demoExists) {
    await User.create({ name:'Demo Student', email:'demo@student.com', passwordHash: await bcrypt.hash('Demo@123', 12), role:'student' });
    console.log('✅ Demo: demo@student.com / Demo@123');
  }

  await mongoose.disconnect();
  console.log('\n🚀 v10 database seeded and ready!');
}

seed().catch(e => { console.error(e); process.exit(1); });
